package dat.config;

import dat.entities.Book;
import dat.security.entity.Role;
import dat.security.entity.User;
import jakarta.persistence.EntityManagerFactory;

import java.util.ArrayList;
import java.util.List;

public class Populate {

    public static void populateDatabase() {
        EntityManagerFactory emf = HibernateConfig.getEntityManagerFactory("books");

        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();

            // Clear existing data
            em.createQuery("DELETE FROM Book").executeUpdate();
            em.createQuery("DELETE FROM User").executeUpdate();
            em.createQuery("DELETE FROM Role").executeUpdate();

            // Create Books
            List<Book> books = getBooks();
            for (Book book : books) {
                em.persist(book);
            }

            // Create Roles
            Role userRole = new Role("user");
            Role adminRole = new Role("admin");
            em.persist(userRole);
            em.persist(adminRole);

            // Create Users
            User user = new User("user", "user123");
            user.addRole(userRole);
            em.persist(user);

            User admin = new User("admin", "admin123");
            admin.addRole(adminRole);
            em.persist(admin);

            em.getTransaction().commit();
        }
    }

    private static List<Book> getBooks() {
        List<Book> books = new ArrayList<>();

        // 500 bøger fra forskellige genrer
        books.add(new Book("To Kill a Mockingbird", "Harper Lee", "J.B. Lippincott & Co.", 1960, Book.Genre.FICTION));
        books.add(new Book("1984", "George Orwell", "Secker & Warburg", 1949, Book.Genre.FICTION));
        books.add(new Book("Pride and Prejudice", "Jane Austen", "T. Egerton", 1813, Book.Genre.ROMANCE));
        books.add(new Book("The Great Gatsby", "F. Scott Fitzgerald", "Charles Scribner's Sons", 1925, Book.Genre.FICTION));
        books.add(new Book("One Hundred Years of Solitude", "Gabriel Garcia Marquez", "Harper & Row", 1967, Book.Genre.FICTION));
        books.add(new Book("Moby Dick", "Herman Melville", "Richard Bentley", 1851, Book.Genre.FICTION));
        books.add(new Book("War and Peace", "Leo Tolstoy", "The Russian Messenger", 1869, Book.Genre.FICTION));
        books.add(new Book("The Catcher in the Rye", "J.D. Salinger", "Little, Brown and Company", 1951, Book.Genre.FICTION));
        books.add(new Book("The Lord of the Rings", "J.R.R. Tolkien", "Allen & Unwin", 1954, Book.Genre.FANTASY));
        books.add(new Book("Harry Potter and the Philosopher's Stone", "J.K. Rowling", "Bloomsbury", 1997, Book.Genre.FANTASY));
        books.add(new Book("The Hobbit", "J.R.R. Tolkien", "Allen & Unwin", 1937, Book.Genre.FANTASY));
        books.add(new Book("Fahrenheit 451", "Ray Bradbury", "Ballantine Books", 1953, Book.Genre.FICTION));
        books.add(new Book("Brave New World", "Aldous Huxley", "Chatto & Windus", 1932, Book.Genre.FICTION));
        books.add(new Book("The Chronicles of Narnia", "C.S. Lewis", "Geoffrey Bles", 1950, Book.Genre.FANTASY));
        books.add(new Book("Jane Eyre", "Charlotte Bronte", "Smith, Elder & Co.", 1847, Book.Genre.ROMANCE));
        books.add(new Book("Wuthering Heights", "Emily Bronte", "Thomas Cautley Newby", 1847, Book.Genre.ROMANCE));
        books.add(new Book("Animal Farm", "George Orwell", "Secker & Warburg", 1945, Book.Genre.FICTION));
        books.add(new Book("The Odyssey", "Homer", "Ancient Greece", -700, Book.Genre.FICTION));
        books.add(new Book("The Iliad", "Homer", "Ancient Greece", -750, Book.Genre.FICTION));
        books.add(new Book("Crime and Punishment", "Fyodor Dostoevsky", "The Russian Messenger", 1866, Book.Genre.FICTION));
        books.add(new Book("The Brothers Karamazov", "Fyodor Dostoevsky", "The Russian Messenger", 1880, Book.Genre.FICTION));
        books.add(new Book("The Picture of Dorian Gray", "Oscar Wilde", "Ward, Lock and Company", 1890, Book.Genre.FICTION));
        books.add(new Book("Dracula", "Bram Stoker", "Archibald Constable", 1897, Book.Genre.HORROR));
        books.add(new Book("Frankenstein", "Mary Shelley", "Lackington, Hughes", 1818, Book.Genre.HORROR));
        books.add(new Book("The Shining", "Stephen King", "Doubleday", 1977, Book.Genre.HORROR));
        books.add(new Book("It", "Stephen King", "Viking Press", 1986, Book.Genre.HORROR));
        books.add(new Book("The Stand", "Stephen King", "Doubleday", 1978, Book.Genre.HORROR));
        books.add(new Book("The Da Vinci Code", "Dan Brown", "Doubleday", 2003, Book.Genre.THRILLER));
        books.add(new Book("Angels and Demons", "Dan Brown", "Pocket Books", 2000, Book.Genre.THRILLER));
        books.add(new Book("The Girl with the Dragon Tattoo", "Stieg Larsson", "Norstedts Forlag", 2005, Book.Genre.MYSTERY));
        books.add(new Book("Gone Girl", "Gillian Flynn", "Crown Publishing", 2012, Book.Genre.THRILLER));
        books.add(new Book("The Hunger Games", "Suzanne Collins", "Scholastic Press", 2008, Book.Genre.FICTION));
        books.add(new Book("Catching Fire", "Suzanne Collins", "Scholastic Press", 2009, Book.Genre.FICTION));
        books.add(new Book("Mockingjay", "Suzanne Collins", "Scholastic Press", 2010, Book.Genre.FICTION));
        books.add(new Book("Twilight", "Stephenie Meyer", "Little, Brown", 2005, Book.Genre.ROMANCE));
        books.add(new Book("The Kite Runner", "Khaled Hosseini", "Riverhead Books", 2003, Book.Genre.FICTION));
        books.add(new Book("A Thousand Splendid Suns", "Khaled Hosseini", "Riverhead Books", 2007, Book.Genre.FICTION));
        books.add(new Book("The Book Thief", "Markus Zusak", "Picador", 2005, Book.Genre.FICTION));
        books.add(new Book("Life of Pi", "Yann Martel", "Knopf Canada", 2001, Book.Genre.FICTION));
        books.add(new Book("The Alchemist", "Paulo Coelho", "HarperCollins", 1988, Book.Genre.FICTION));
        books.add(new Book("The Little Prince", "Antoine de Saint-Exupery", "Reynal & Hitchcock", 1943, Book.Genre.FICTION));
        books.add(new Book("Sapiens", "Yuval Noah Harari", "Harvill Secker", 2011, Book.Genre.NONFICTION));
        books.add(new Book("Homo Deus", "Yuval Noah Harari", "Harvill Secker", 2015, Book.Genre.NONFICTION));
        books.add(new Book("Educated", "Tara Westover", "Random House", 2018, Book.Genre.BIOGRAPHY));
        books.add(new Book("Becoming", "Michelle Obama", "Crown Publishing", 2018, Book.Genre.BIOGRAPHY));
        books.add(new Book("The Diary of a Young Girl", "Anne Frank", "Contact Publishing", 1947, Book.Genre.BIOGRAPHY));
        books.add(new Book("Long Walk to Freedom", "Nelson Mandela", "Little, Brown", 1994, Book.Genre.BIOGRAPHY));
        books.add(new Book("Steve Jobs", "Walter Isaacson", "Simon & Schuster", 2011, Book.Genre.BIOGRAPHY));
        books.add(new Book("Einstein: His Life and Universe", "Walter Isaacson", "Simon & Schuster", 2007, Book.Genre.BIOGRAPHY));
        books.add(new Book("A Brief History of Time", "Stephen Hawking", "Bantam Dell", 1988, Book.Genre.SCIENCE));
        books.add(new Book("The Origin of Species", "Charles Darwin", "John Murray", 1859, Book.Genre.SCIENCE));
        books.add(new Book("The Selfish Gene", "Richard Dawkins", "Oxford University Press", 1976, Book.Genre.SCIENCE));
        books.add(new Book("Cosmos", "Carl Sagan", "Random House", 1980, Book.Genre.SCIENCE));
        books.add(new Book("The Double Helix", "James Watson", "Atheneum", 1968, Book.Genre.SCIENCE));
        books.add(new Book("Guns, Germs, and Steel", "Jared Diamond", "W.W. Norton", 1997, Book.Genre.HISTORY));
        books.add(new Book("The Histories", "Herodotus", "Ancient Greece", -440, Book.Genre.HISTORY));
        books.add(new Book("The History of the Decline and Fall of the Roman Empire", "Edward Gibbon", "Strahan & Cadell", 1776, Book.Genre.HISTORY));
        books.add(new Book("A People's History of the United States", "Howard Zinn", "Harper & Row", 1980, Book.Genre.HISTORY));
        books.add(new Book("The Wright Brothers", "David McCullough", "Simon & Schuster", 2015, Book.Genre.HISTORY));
        books.add(new Book("1776", "David McCullough", "Simon & Schuster", 2005, Book.Genre.HISTORY));
        books.add(new Book("Team of Rivals", "Doris Kearns Goodwin", "Simon & Schuster", 2005, Book.Genre.HISTORY));
        books.add(new Book("The Second World War", "Winston Churchill", "Cassell & Co", 1948, Book.Genre.HISTORY));
        books.add(new Book("The Rise and Fall of the Third Reich", "William Shirer", "Simon & Schuster", 1960, Book.Genre.HISTORY));
        books.add(new Book("The Guns of August", "Barbara Tuchman", "Macmillan", 1962, Book.Genre.HISTORY));
        books.add(new Book("Night", "Elie Wiesel", "Hill & Wang", 1960, Book.Genre.BIOGRAPHY));
        books.add(new Book("Man's Search for Meaning", "Viktor Frankl", "Beacon Press", 1946, Book.Genre.NONFICTION));
        books.add(new Book("The Art of War", "Sun Tzu", "Ancient China", -500, Book.Genre.NONFICTION));
        books.add(new Book("The Prince", "Niccolo Machiavelli", "Antonio Blado", 1532, Book.Genre.NONFICTION));
        books.add(new Book("Meditations", "Marcus Aurelius", "Ancient Rome", 180, Book.Genre.NONFICTION));
        books.add(new Book("The Republic", "Plato", "Ancient Greece", -375, Book.Genre.NONFICTION));
        books.add(new Book("The Communist Manifesto", "Karl Marx", "Workers Educational Association", 1848, Book.Genre.NONFICTION));
        books.add(new Book("The Wealth of Nations", "Adam Smith", "W. Strahan and T. Cadell", 1776, Book.Genre.NONFICTION));
        books.add(new Book("On the Origin of Species", "Charles Darwin", "John Murray", 1859, Book.Genre.SCIENCE));
        books.add(new Book("The Interpretation of Dreams", "Sigmund Freud", "Franz Deuticke", 1899, Book.Genre.NONFICTION));
        books.add(new Book("Thinking, Fast and Slow", "Daniel Kahneman", "Farrar, Straus and Giroux", 2011, Book.Genre.NONFICTION));
        books.add(new Book("The Power of Habit", "Charles Duhigg", "Random House", 2012, Book.Genre.NONFICTION));
        books.add(new Book("Outliers", "Malcolm Gladwell", "Little, Brown", 2008, Book.Genre.NONFICTION));
        books.add(new Book("Blink", "Malcolm Gladwell", "Little, Brown", 2005, Book.Genre.NONFICTION));
        books.add(new Book("The Tipping Point", "Malcolm Gladwell", "Little, Brown", 2000, Book.Genre.NONFICTION));
        books.add(new Book("Freakonomics", "Steven Levitt", "William Morrow", 2005, Book.Genre.NONFICTION));
        books.add(new Book("The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "Crown Publishing", 2010, Book.Genre.NONFICTION));
        books.add(new Book("Into the Wild", "Jon Krakauer", "Villard", 1996, Book.Genre.NONFICTION));
        books.add(new Book("Into Thin Air", "Jon Krakauer", "Villard", 1997, Book.Genre.NONFICTION));
        books.add(new Book("Unbroken", "Laura Hillenbrand", "Random House", 2010, Book.Genre.BIOGRAPHY));
        books.add(new Book("Seabiscuit", "Laura Hillenbrand", "Random House", 2001, Book.Genre.BIOGRAPHY));
        books.add(new Book("The Glass Castle", "Jeannette Walls", "Scribner", 2005, Book.Genre.BIOGRAPHY));
        books.add(new Book("Wild", "Cheryl Strayed", "Alfred A. Knopf", 2012, Book.Genre.BIOGRAPHY));
        books.add(new Book("Eat, Pray, Love", "Elizabeth Gilbert", "Viking Press", 2006, Book.Genre.BIOGRAPHY));
        books.add(new Book("The Fault in Our Stars", "John Green", "Dutton Books", 2012, Book.Genre.FICTION));
        books.add(new Book("Looking for Alaska", "John Green", "Dutton Books", 2005, Book.Genre.FICTION));
        books.add(new Book("Paper Towns", "John Green", "Dutton Books", 2008, Book.Genre.FICTION));
        books.add(new Book("The Perks of Being a Wallflower", "Stephen Chbosky", "MTV Books", 1999, Book.Genre.FICTION));
        books.add(new Book("The Giver", "Lois Lowry", "Houghton Mifflin", 1993, Book.Genre.FICTION));
        books.add(new Book("Ender's Game", "Orson Scott Card", "Tor Books", 1985, Book.Genre.FICTION));
        books.add(new Book("Dune", "Frank Herbert", "Chilton Books", 1965, Book.Genre.FICTION));
        books.add(new Book("Foundation", "Isaac Asimov", "Gnome Press", 1951, Book.Genre.FICTION));
        books.add(new Book("Neuromancer", "William Gibson", "Ace Books", 1984, Book.Genre.FICTION));
        books.add(new Book("Snow Crash", "Neal Stephenson", "Bantam Books", 1992, Book.Genre.FICTION));
        books.add(new Book("The Martian", "Andy Weir", "Crown Publishing", 2011, Book.Genre.FICTION));
        books.add(new Book("Ready Player One", "Ernest Cline", "Crown Publishing", 2011, Book.Genre.FICTION));
        books.add(new Book("The Handmaid's Tale", "Margaret Atwood", "McClelland and Stewart", 1985, Book.Genre.FICTION));
        books.add(new Book("The Road", "Cormac McCarthy", "Alfred A. Knopf", 2006, Book.Genre.FICTION));
        books.add(new Book("All the Light We Cannot See", "Anthony Doerr", "Scribner", 2014, Book.Genre.FICTION));
        books.add(new Book("The Nightingale", "Kristin Hannah", "St. Martin's Press", 2015, Book.Genre.FICTION));
        books.add(new Book("The Help", "Kathryn Stockett", "Penguin Books", 2009, Book.Genre.FICTION));
        books.add(new Book("The Secret Life of Bees", "Sue Monk Kidd", "Viking Press", 2002, Book.Genre.FICTION));
        books.add(new Book("Water for Elephants", "Sara Gruen", "Algonquin Books", 2006, Book.Genre.FICTION));
        books.add(new Book("The Time Traveler's Wife", "Audrey Niffenegger", "MacAdam/Cage", 2003, Book.Genre.ROMANCE));
        books.add(new Book("The Notebook", "Nicholas Sparks", "Warner Books", 1996, Book.Genre.ROMANCE));
        books.add(new Book("A Walk to Remember", "Nicholas Sparks", "Warner Books", 1999, Book.Genre.ROMANCE));
        books.add(new Book("Dear John", "Nicholas Sparks", "Warner Books", 2006, Book.Genre.ROMANCE));
        books.add(new Book("Me Before You", "Jojo Moyes", "Penguin Books", 2012, Book.Genre.ROMANCE));
        books.add(new Book("The Rosie Project", "Graeme Simsion", "Text Publishing", 2013, Book.Genre.ROMANCE));
        books.add(new Book("Eleanor & Park", "Rainbow Rowell", "St. Martin's Press", 2013, Book.Genre.ROMANCE));
        books.add(new Book("Attachments", "Rainbow Rowell", "Dutton Books", 2011, Book.Genre.ROMANCE));
        books.add(new Book("The Hating Game", "Sally Thorne", "William Morrow", 2016, Book.Genre.ROMANCE));
        books.add(new Book("Outlander", "Diana Gabaldon", "Delacorte Press", 1991, Book.Genre.ROMANCE));
        books.add(new Book("A Game of Thrones", "George R.R. Martin", "Bantam Spectra", 1996, Book.Genre.FANTASY));
        books.add(new Book("A Clash of Kings", "George R.R. Martin", "Bantam Spectra", 1998, Book.Genre.FANTASY));
        books.add(new Book("A Storm of Swords", "George R.R. Martin", "Bantam Spectra", 2000, Book.Genre.FANTASY));
        books.add(new Book("The Name of the Wind", "Patrick Rothfuss", "DAW Books", 2007, Book.Genre.FANTASY));
        books.add(new Book("The Wise Man's Fear", "Patrick Rothfuss", "DAW Books", 2011, Book.Genre.FANTASY));
        books.add(new Book("The Way of Kings", "Brandon Sanderson", "Tor Books", 2010, Book.Genre.FANTASY));
        books.add(new Book("Mistborn", "Brandon Sanderson", "Tor Books", 2006, Book.Genre.FANTASY));
        books.add(new Book("The Final Empire", "Brandon Sanderson", "Tor Books", 2006, Book.Genre.FANTASY));
        books.add(new Book("American Gods", "Neil Gaiman", "William Morrow", 2001, Book.Genre.FANTASY));
        books.add(new Book("Good Omens", "Neil Gaiman", "William Morrow", 1990, Book.Genre.FANTASY));
        books.add(new Book("The Graveyard Book", "Neil Gaiman", "HarperCollins", 2008, Book.Genre.FANTASY));
        books.add(new Book("Coraline", "Neil Gaiman", "HarperCollins", 2002, Book.Genre.FANTASY));
        books.add(new Book("The Ocean at the End of the Lane", "Neil Gaiman", "William Morrow", 2013, Book.Genre.FANTASY));
        books.add(new Book("Stardust", "Neil Gaiman", "Avon Books", 1999, Book.Genre.FANTASY));
        books.add(new Book("The Night Circus", "Erin Morgenstern", "Doubleday", 2011, Book.Genre.FANTASY));
        books.add(new Book("The Shadow of the Wind", "Carlos Ruiz Zafon", "Penguin Books", 2001, Book.Genre.MYSTERY));
        books.add(new Book("The Name of the Rose", "Umberto Eco", "Bompiani", 1980, Book.Genre.MYSTERY));
        books.add(new Book("The Hound of the Baskervilles", "Arthur Conan Doyle", "George Newnes", 1902, Book.Genre.MYSTERY));
        books.add(new Book("Murder on the Orient Express", "Agatha Christie", "Collins Crime Club", 1934, Book.Genre.MYSTERY));
        books.add(new Book("And Then There Were None", "Agatha Christie", "Collins Crime Club", 1939, Book.Genre.MYSTERY));
        books.add(new Book("The Murder of Roger Ackroyd", "Agatha Christie", "William Collins", 1926, Book.Genre.MYSTERY));
        books.add(new Book("Death on the Nile", "Agatha Christie", "Collins Crime Club", 1937, Book.Genre.MYSTERY));
        books.add(new Book("The ABC Murders", "Agatha Christie", "Collins Crime Club", 1936, Book.Genre.MYSTERY));
        books.add(new Book("The Big Sleep", "Raymond Chandler", "Alfred A. Knopf", 1939, Book.Genre.MYSTERY));
        books.add(new Book("The Maltese Falcon", "Dashiell Hammett", "Alfred A. Knopf", 1930, Book.Genre.MYSTERY));
        books.add(new Book("The Silence of the Lambs", "Thomas Harris", "St. Martin's Press", 1988, Book.Genre.THRILLER));
        books.add(new Book("Red Dragon", "Thomas Harris", "Putnam", 1981, Book.Genre.THRILLER));
        books.add(new Book("Hannibal", "Thomas Harris", "Delacorte Press", 1999, Book.Genre.THRILLER));
        books.add(new Book("The Firm", "John Grisham", "Doubleday", 1991, Book.Genre.THRILLER));
        books.add(new Book("A Time to Kill", "John Grisham", "Wynwood Press", 1989, Book.Genre.THRILLER));
        books.add(new Book("The Pelican Brief", "John Grisham", "Doubleday", 1992, Book.Genre.THRILLER));
        books.add(new Book("The Client", "John Grisham", "Doubleday", 1993, Book.Genre.THRILLER));
        books.add(new Book("The Rainmaker", "John Grisham", "Doubleday", 1995, Book.Genre.THRILLER));
        books.add(new Book("The Bourne Identity", "Robert Ludlum", "Richard Marek", 1980, Book.Genre.THRILLER));
        books.add(new Book("The Hunt for Red October", "Tom Clancy", "Naval Institute Press", 1984, Book.Genre.THRILLER));
        books.add(new Book("Patriot Games", "Tom Clancy", "Putnam", 1987, Book.Genre.THRILLER));
        books.add(new Book("Clear and Present Danger", "Tom Clancy", "Putnam", 1989, Book.Genre.THRILLER));
        books.add(new Book("The Sum of All Fears", "Tom Clancy", "Putnam", 1991, Book.Genre.THRILLER));
        books.add(new Book("Without Remorse", "Tom Clancy", "Putnam", 1993, Book.Genre.THRILLER));
        books.add(new Book("The Shining", "Stephen King", "Doubleday", 1977, Book.Genre.HORROR));
        books.add(new Book("The Stand", "Stephen King", "Doubleday", 1978, Book.Genre.HORROR));
        books.add(new Book("Carrie", "Stephen King", "Doubleday", 1974, Book.Genre.HORROR));
        books.add(new Book("Salem's Lot", "Stephen King", "Doubleday", 1975, Book.Genre.HORROR));
        books.add(new Book("Pet Sematary", "Stephen King", "Doubleday", 1983, Book.Genre.HORROR));
        books.add(new Book("Misery", "Stephen King", "Viking Press", 1987, Book.Genre.HORROR));
        books.add(new Book("The Green Mile", "Stephen King", "Signet Books", 1996, Book.Genre.FICTION));
        books.add(new Book("The Dead Zone", "Stephen King", "Viking Press", 1979, Book.Genre.HORROR));
        books.add(new Book("Christine", "Stephen King", "Viking Press", 1983, Book.Genre.HORROR));
        books.add(new Book("Cujo", "Stephen King", "Viking Press", 1981, Book.Genre.HORROR));
        books.add(new Book("Firestarter", "Stephen King", "Viking Press", 1980, Book.Genre.HORROR));
        books.add(new Book("The Dark Tower", "Stephen King", "Donald M. Grant", 1982, Book.Genre.FANTASY));
        books.add(new Book("11/22/63", "Stephen King", "Scribner", 2011, Book.Genre.FICTION));
        books.add(new Book("Under the Dome", "Stephen King", "Scribner", 2009, Book.Genre.FICTION));
        books.add(new Book("Doctor Sleep", "Stephen King", "Scribner", 2013, Book.Genre.HORROR));
        books.add(new Book("The Outsider", "Stephen King", "Scribner", 2018, Book.Genre.HORROR));
        books.add(new Book("The Institute", "Stephen King", "Scribner", 2019, Book.Genre.THRILLER));
        books.add(new Book("Later", "Stephen King", "Hard Case Crime", 2021, Book.Genre.THRILLER));
        books.add(new Book("Billy Summers", "Stephen King", "Scribner", 2021, Book.Genre.THRILLER));
        books.add(new Book("Fairy Tale", "Stephen King", "Scribner", 2022, Book.Genre.FANTASY));
        books.add(new Book("Holly", "Stephen King", "Scribner", 2023, Book.Genre.THRILLER));
        books.add(new Book("The Exorcist", "William Peter Blatty", "Harper & Row", 1971, Book.Genre.HORROR));
        books.add(new Book("The Haunting of Hill House", "Shirley Jackson", "Viking Press", 1959, Book.Genre.HORROR));
        books.add(new Book("We Have Always Lived in the Castle", "Shirley Jackson", "Viking Press", 1962, Book.Genre.HORROR));
        books.add(new Book("The Lottery", "Shirley Jackson", "Farrar, Straus", 1949, Book.Genre.HORROR));
        books.add(new Book("Interview with the Vampire", "Anne Rice", "Alfred A. Knopf", 1976, Book.Genre.HORROR));
        books.add(new Book("The Vampire Lestat", "Anne Rice", "Alfred A. Knopf", 1985, Book.Genre.HORROR));
        books.add(new Book("Queen of the Damned", "Anne Rice", "Alfred A. Knopf", 1988, Book.Genre.HORROR));
        books.add(new Book("The Witching Hour", "Anne Rice", "Alfred A. Knopf", 1990, Book.Genre.HORROR));
        books.add(new Book("The Mummy", "Anne Rice", "Ballantine Books", 1989, Book.Genre.HORROR));
        books.add(new Book("The Wolf Gift", "Anne Rice", "Alfred A. Knopf", 2012, Book.Genre.HORROR));
        books.add(new Book("Prince Lestat", "Anne Rice", "Alfred A. Knopf", 2014, Book.Genre.HORROR));
        books.add(new Book("Rosemary's Baby", "Ira Levin", "Random House", 1967, Book.Genre.HORROR));
        books.add(new Book("The Stepford Wives", "Ira Levin", "Random House", 1972, Book.Genre.HORROR));
        books.add(new Book("The Boys from Brazil", "Ira Levin", "Random House", 1976, Book.Genre.THRILLER));
        books.add(new Book("A Kiss Before Dying", "Ira Levin", "Simon & Schuster", 1953, Book.Genre.THRILLER));
        books.add(new Book("The Amityville Horror", "Jay Anson", "Prentice Hall", 1977, Book.Genre.HORROR));
        books.add(new Book("The Omen", "David Seltzer", "Signet Books", 1976, Book.Genre.HORROR));
        books.add(new Book("Hell House", "Richard Matheson", "Viking Press", 1971, Book.Genre.HORROR));
        books.add(new Book("I Am Legend", "Richard Matheson", "Gold Medal Books", 1954, Book.Genre.HORROR));
        books.add(new Book("The Shrinking Man", "Richard Matheson", "Gold Medal Books", 1956, Book.Genre.FICTION));
        books.add(new Book("What Dreams May Come", "Richard Matheson", "Putnam", 1978, Book.Genre.FICTION));
        books.add(new Book("Bid Time Return", "Richard Matheson", "Viking Press", 1975, Book.Genre.ROMANCE));
        books.add(new Book("A Stir of Echoes", "Richard Matheson", "Lippincott", 1958, Book.Genre.HORROR));
        books.add(new Book("The Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson", "Longmans, Green", 1886, Book.Genre.HORROR));
        books.add(new Book("Treasure Island", "Robert Louis Stevenson", "Cassell & Company", 1883, Book.Genre.FICTION));
        books.add(new Book("Kidnapped", "Robert Louis Stevenson", "Cassell & Company", 1886, Book.Genre.FICTION));
        books.add(new Book("The Black Arrow", "Robert Louis Stevenson", "Cassell & Company", 1888, Book.Genre.FICTION));
        books.add(new Book("Robinson Crusoe", "Daniel Defoe", "William Taylor", 1719, Book.Genre.FICTION));
        books.add(new Book("Gulliver's Travels", "Jonathan Swift", "Benjamin Motte", 1726, Book.Genre.FICTION));
        books.add(new Book("Don Quixote", "Miguel de Cervantes", "Francisco de Robles", 1605, Book.Genre.FICTION));
        books.add(new Book("The Three Musketeers", "Alexandre Dumas", "Le Siecle", 1844, Book.Genre.FICTION));
        books.add(new Book("The Count of Monte Cristo", "Alexandre Dumas", "Petion", 1844, Book.Genre.FICTION));
        books.add(new Book("The Man in the Iron Mask", "Alexandre Dumas", "Le Siecle", 1847, Book.Genre.FICTION));
        books.add(new Book("Twenty Thousand Leagues Under the Sea", "Jules Verne", "Pierre-Jules Hetzel", 1870, Book.Genre.FICTION));
        books.add(new Book("Around the World in Eighty Days", "Jules Verne", "Pierre-Jules Hetzel", 1873, Book.Genre.FICTION));
        books.add(new Book("Journey to the Center of the Earth", "Jules Verne", "Pierre-Jules Hetzel", 1864, Book.Genre.FICTION));
        books.add(new Book("The Mysterious Island", "Jules Verne", "Pierre-Jules Hetzel", 1874, Book.Genre.FICTION));
        books.add(new Book("From the Earth to the Moon", "Jules Verne", "Pierre-Jules Hetzel", 1865, Book.Genre.FICTION));
        books.add(new Book("The Time Machine", "H.G. Wells", "William Heinemann", 1895, Book.Genre.FICTION));
        books.add(new Book("The War of the Worlds", "H.G. Wells", "William Heinemann", 1898, Book.Genre.FICTION));
        books.add(new Book("The Invisible Man", "H.G. Wells", "C. Arthur Pearson", 1897, Book.Genre.FICTION));
        books.add(new Book("The Island of Doctor Moreau", "H.G. Wells", "William Heinemann", 1896, Book.Genre.FICTION));
        books.add(new Book("The First Men in the Moon", "H.G. Wells", "George Newnes", 1901, Book.Genre.FICTION));
        books.add(new Book("The Food of the Gods", "H.G. Wells", "Macmillan", 1904, Book.Genre.FICTION));
        books.add(new Book("In the Days of the Comet", "H.G. Wells", "Macmillan", 1906, Book.Genre.FICTION));
        books.add(new Book("The Shape of Things to Come", "H.G. Wells", "Hutchinson", 1933, Book.Genre.FICTION));
        books.add(new Book("The Sleeper Awakes", "H.G. Wells", "Harper & Brothers", 1899, Book.Genre.FICTION));
        books.add(new Book("A Connecticut Yankee in King Arthur's Court", "Mark Twain", "Charles L. Webster", 1889, Book.Genre.FICTION));
        books.add(new Book("The Adventures of Tom Sawyer", "Mark Twain", "American Publishing Company", 1876, Book.Genre.FICTION));
        books.add(new Book("Adventures of Huckleberry Finn", "Mark Twain", "Chatto & Windus", 1884, Book.Genre.FICTION));
        books.add(new Book("The Prince and the Pauper", "Mark Twain", "James R. Osgood", 1881, Book.Genre.FICTION));
        books.add(new Book("A Tale of Two Cities", "Charles Dickens", "Chapman & Hall", 1859, Book.Genre.FICTION));
        books.add(new Book("Great Expectations", "Charles Dickens", "Chapman & Hall", 1861, Book.Genre.FICTION));
        books.add(new Book("Oliver Twist", "Charles Dickens", "Richard Bentley", 1838, Book.Genre.FICTION));
        books.add(new Book("David Copperfield", "Charles Dickens", "Bradbury & Evans", 1850, Book.Genre.FICTION));
        books.add(new Book("A Christmas Carol", "Charles Dickens", "Chapman & Hall", 1843, Book.Genre.FICTION));
        books.add(new Book("Bleak House", "Charles Dickens", "Bradbury & Evans", 1853, Book.Genre.FICTION));
        books.add(new Book("Hard Times", "Charles Dickens", "Bradbury & Evans", 1854, Book.Genre.FICTION));
        books.add(new Book("Little Dorrit", "Charles Dickens", "Bradbury & Evans", 1857, Book.Genre.FICTION));
        books.add(new Book("Our Mutual Friend", "Charles Dickens", "Chapman & Hall", 1865, Book.Genre.FICTION));
        books.add(new Book("The Pickwick Papers", "Charles Dickens", "Chapman & Hall", 1837, Book.Genre.FICTION));
        books.add(new Book("Nicholas Nickleby", "Charles Dickens", "Chapman & Hall", 1839, Book.Genre.FICTION));
        books.add(new Book("The Old Curiosity Shop", "Charles Dickens", "Chapman & Hall", 1841, Book.Genre.FICTION));
        books.add(new Book("Barnaby Rudge", "Charles Dickens", "Chapman & Hall", 1841, Book.Genre.FICTION));
        books.add(new Book("Martin Chuzzlewit", "Charles Dickens", "Chapman & Hall", 1844, Book.Genre.FICTION));
        books.add(new Book("Dombey and Son", "Charles Dickens", "Bradbury & Evans", 1848, Book.Genre.FICTION));
        books.add(new Book("The Mystery of Edwin Drood", "Charles Dickens", "Chapman & Hall", 1870, Book.Genre.MYSTERY));
        books.add(new Book("Sense and Sensibility", "Jane Austen", "Thomas Egerton", 1811, Book.Genre.ROMANCE));
        books.add(new Book("Emma", "Jane Austen", "John Murray", 1815, Book.Genre.ROMANCE));
        books.add(new Book("Mansfield Park", "Jane Austen", "Thomas Egerton", 1814, Book.Genre.ROMANCE));
        books.add(new Book("Northanger Abbey", "Jane Austen", "John Murray", 1817, Book.Genre.ROMANCE));
        books.add(new Book("Persuasion", "Jane Austen", "John Murray", 1817, Book.Genre.ROMANCE));
        books.add(new Book("Lady Susan", "Jane Austen", "J.E. Austen-Leigh", 1871, Book.Genre.FICTION));
        books.add(new Book("The Scarlet Letter", "Nathaniel Hawthorne", "Ticknor, Reed & Fields", 1850, Book.Genre.FICTION));
        books.add(new Book("The House of the Seven Gables", "Nathaniel Hawthorne", "Ticknor, Reed & Fields", 1851, Book.Genre.FICTION));
        books.add(new Book("The Blithedale Romance", "Nathaniel Hawthorne", "Ticknor, Reed & Fields", 1852, Book.Genre.FICTION));
        books.add(new Book("The Marble Faun", "Nathaniel Hawthorne", "Ticknor and Fields", 1860, Book.Genre.FICTION));
        books.add(new Book("Twice-Told Tales", "Nathaniel Hawthorne", "American Stationers Company", 1837, Book.Genre.FICTION));
        books.add(new Book("Mosses from an Old Manse", "Nathaniel Hawthorne", "Wiley and Putnam", 1846, Book.Genre.FICTION));
        books.add(new Book("The Snow-Image", "Nathaniel Hawthorne", "Ticknor, Reed & Fields", 1851, Book.Genre.FICTION));
        books.add(new Book("Uncle Tom's Cabin", "Harriet Beecher Stowe", "John P. Jewett", 1852, Book.Genre.FICTION));
        books.add(new Book("Little Women", "Louisa May Alcott", "Roberts Brothers", 1868, Book.Genre.FICTION));
        books.add(new Book("Little Men", "Louisa May Alcott", "Roberts Brothers", 1871, Book.Genre.FICTION));
        books.add(new Book("Jo's Boys", "Louisa May Alcott", "Roberts Brothers", 1886, Book.Genre.FICTION));
        books.add(new Book("An Old-Fashioned Girl", "Louisa May Alcott", "Roberts Brothers", 1870, Book.Genre.FICTION));
        books.add(new Book("Eight Cousins", "Louisa May Alcott", "Roberts Brothers", 1875, Book.Genre.FICTION));
        books.add(new Book("Rose in Bloom", "Louisa May Alcott", "Roberts Brothers", 1876, Book.Genre.FICTION));
        books.add(new Book("Under the Lilacs", "Louisa May Alcott", "Roberts Brothers", 1878, Book.Genre.FICTION));
        books.add(new Book("Jack and Jill", "Louisa May Alcott", "Roberts Brothers", 1880, Book.Genre.FICTION));
        books.add(new Book("The Secret Garden", "Frances Hodgson Burnett", "Frederick A. Stokes", 1911, Book.Genre.FICTION));
        books.add(new Book("A Little Princess", "Frances Hodgson Burnett", "Charles Scribner's Sons", 1905, Book.Genre.FICTION));
        books.add(new Book("Little Lord Fauntleroy", "Frances Hodgson Burnett", "Charles Scribner's Sons", 1886, Book.Genre.FICTION));
        books.add(new Book("The Lost Prince", "Frances Hodgson Burnett", "The Century Company", 1915, Book.Genre.FICTION));
        books.add(new Book("Anne of Green Gables", "L.M. Montgomery", "L.C. Page & Co", 1908, Book.Genre.FICTION));
        books.add(new Book("Anne of Avonlea", "L.M. Montgomery", "L.C. Page & Co", 1909, Book.Genre.FICTION));
        books.add(new Book("Anne of the Island", "L.M. Montgomery", "L.C. Page & Co", 1915, Book.Genre.FICTION));
        books.add(new Book("Anne of Windy Poplars", "L.M. Montgomery", "Frederick A. Stokes", 1936, Book.Genre.FICTION));
        books.add(new Book("Anne's House of Dreams", "L.M. Montgomery", "Frederick A. Stokes", 1917, Book.Genre.FICTION));
        books.add(new Book("Anne of Ingleside", "L.M. Montgomery", "Frederick A. Stokes", 1939, Book.Genre.FICTION));
        books.add(new Book("Rainbow Valley", "L.M. Montgomery", "Frederick A. Stokes", 1919, Book.Genre.FICTION));
        books.add(new Book("Rilla of Ingleside", "L.M. Montgomery", "Frederick A. Stokes", 1921, Book.Genre.FICTION));
        books.add(new Book("Emily of New Moon", "L.M. Montgomery", "Frederick A. Stokes", 1923, Book.Genre.FICTION));
        books.add(new Book("Emily Climbs", "L.M. Montgomery", "Frederick A. Stokes", 1925, Book.Genre.FICTION));
        books.add(new Book("Emily's Quest", "L.M. Montgomery", "Frederick A. Stokes", 1927, Book.Genre.FICTION));
        books.add(new Book("The Blue Castle", "L.M. Montgomery", "Frederick A. Stokes", 1926, Book.Genre.FICTION));
        books.add(new Book("The Story Girl", "L.M. Montgomery", "L.C. Page & Co", 1911, Book.Genre.FICTION));
        books.add(new Book("The Golden Road", "L.M. Montgomery", "L.C. Page & Co", 1913, Book.Genre.FICTION));
        books.add(new Book("Heidi", "Johanna Spyri", "Perthes", 1881, Book.Genre.FICTION));
        books.add(new Book("The Swiss Family Robinson", "Johann David Wyss", "M. Godwin", 1812, Book.Genre.FICTION));
        books.add(new Book("Black Beauty", "Anna Sewell", "Jarrold and Sons", 1877, Book.Genre.FICTION));
        books.add(new Book("The Jungle Book", "Rudyard Kipling", "Macmillan", 1894, Book.Genre.FICTION));
        books.add(new Book("The Second Jungle Book", "Rudyard Kipling", "Macmillan", 1895, Book.Genre.FICTION));
        books.add(new Book("Kim", "Rudyard Kipling", "Macmillan", 1901, Book.Genre.FICTION));
        books.add(new Book("Captains Courageous", "Rudyard Kipling", "Macmillan", 1897, Book.Genre.FICTION));
        books.add(new Book("The Man Who Would Be King", "Rudyard Kipling", "Allahabad Pioneer", 1888, Book.Genre.FICTION));
        books.add(new Book("Just So Stories", "Rudyard Kipling", "Macmillan", 1902, Book.Genre.FICTION));
        books.add(new Book("The Call of the Wild", "Jack London", "Macmillan", 1903, Book.Genre.FICTION));
        books.add(new Book("White Fang", "Jack London", "Macmillan", 1906, Book.Genre.FICTION));
        books.add(new Book("The Sea-Wolf", "Jack London", "Macmillan", 1904, Book.Genre.FICTION));
        books.add(new Book("Martin Eden", "Jack London", "Macmillan", 1909, Book.Genre.FICTION));
        books.add(new Book("The Iron Heel", "Jack London", "Macmillan", 1908, Book.Genre.FICTION));
        books.add(new Book("The Valley of the Moon", "Jack London", "Macmillan", 1913, Book.Genre.FICTION));
        books.add(new Book("The Star Rover", "Jack London", "Macmillan", 1915, Book.Genre.FICTION));
        books.add(new Book("Burning Daylight", "Jack London", "Macmillan", 1910, Book.Genre.FICTION));
        books.add(new Book("John Barleycorn", "Jack London", "The Century Company", 1913, Book.Genre.BIOGRAPHY));
        books.add(new Book("The People of the Abyss", "Jack London", "Macmillan", 1903, Book.Genre.NONFICTION));
        books.add(new Book("The Cruise of the Snark", "Jack London", "Macmillan", 1911, Book.Genre.NONFICTION));
        books.add(new Book("The Red Badge of Courage", "Stephen Crane", "D. Appleton", 1895, Book.Genre.FICTION));
        books.add(new Book("Maggie: A Girl of the Streets", "Stephen Crane", "Stephen Crane", 1893, Book.Genre.FICTION));
        books.add(new Book("The Open Boat", "Stephen Crane", "Doubleday & McClure", 1898, Book.Genre.FICTION));
        books.add(new Book("The Blue Hotel", "Stephen Crane", "Collier's Weekly", 1898, Book.Genre.FICTION));
        books.add(new Book("The Bride Comes to Yellow Sky", "Stephen Crane", "McClure's Magazine", 1898, Book.Genre.FICTION));
        books.add(new Book("The Monster", "Stephen Crane", "Harper's Magazine", 1898, Book.Genre.FICTION));
        books.add(new Book("An Episode of War", "Stephen Crane", "Gentlewoman", 1899, Book.Genre.FICTION));
        books.add(new Book("The Last of the Mohicans", "James Fenimore Cooper", "H.C. Carey & I. Lea", 1826, Book.Genre.FICTION));
        books.add(new Book("The Deerslayer", "James Fenimore Cooper", "Lea and Blanchard", 1841, Book.Genre.FICTION));
        books.add(new Book("The Pathfinder", "James Fenimore Cooper", "Lea and Blanchard", 1840, Book.Genre.FICTION));
        books.add(new Book("The Pioneers", "James Fenimore Cooper", "Charles Wiley", 1823, Book.Genre.FICTION));
        books.add(new Book("The Prairie", "James Fenimore Cooper", "Carey, Lea & Carey", 1827, Book.Genre.FICTION));
        books.add(new Book("The Spy", "James Fenimore Cooper", "Wiley & Halsted", 1821, Book.Genre.FICTION));
        books.add(new Book("The Pilot", "James Fenimore Cooper", "Charles Wiley", 1824, Book.Genre.FICTION));
        books.add(new Book("The Red Rover", "James Fenimore Cooper", "Carey, Lea & Carey", 1827, Book.Genre.FICTION));
        books.add(new Book("The Water-Witch", "James Fenimore Cooper", "Carey & Lea", 1830, Book.Genre.FICTION));
        books.add(new Book("The Bravo", "James Fenimore Cooper", "Carey & Lea", 1831, Book.Genre.FICTION));
        books.add(new Book("The Heidenmauer", "James Fenimore Cooper", "Carey & Lea", 1832, Book.Genre.FICTION));
        books.add(new Book("The Headsman", "James Fenimore Cooper", "Carey, Lea & Blanchard", 1833, Book.Genre.FICTION));
        books.add(new Book("The Monikins", "James Fenimore Cooper", "Carey, Lea & Blanchard", 1835, Book.Genre.FICTION));
        books.add(new Book("Homeward Bound", "James Fenimore Cooper", "Carey, Lea & Blanchard", 1838, Book.Genre.FICTION));
        books.add(new Book("Home as Found", "James Fenimore Cooper", "Lea & Blanchard", 1838, Book.Genre.FICTION));
        books.add(new Book("The Two Admirals", "James Fenimore Cooper", "Lea & Blanchard", 1842, Book.Genre.FICTION));
        books.add(new Book("The Wing-and-Wing", "James Fenimore Cooper", "Lea & Blanchard", 1842, Book.Genre.FICTION));
        books.add(new Book("Wyandotte", "James Fenimore Cooper", "Lea & Blanchard", 1843, Book.Genre.FICTION));
        books.add(new Book("Afloat and Ashore", "James Fenimore Cooper", "Lea & Blanchard", 1844, Book.Genre.FICTION));
        books.add(new Book("Miles Wallingford", "James Fenimore Cooper", "Lea & Blanchard", 1844, Book.Genre.FICTION));
        books.add(new Book("Satanstoe", "James Fenimore Cooper", "Burgess, Stringer & Co", 1845, Book.Genre.FICTION));
        books.add(new Book("The Chainbearer", "James Fenimore Cooper", "Burgess, Stringer & Co", 1845, Book.Genre.FICTION));
        books.add(new Book("The Redskins", "James Fenimore Cooper", "Burgess, Stringer & Co", 1846, Book.Genre.FICTION));
        books.add(new Book("The Crater", "James Fenimore Cooper", "Burgess, Stringer & Co", 1847, Book.Genre.FICTION));
        books.add(new Book("Jack Tier", "James Fenimore Cooper", "Burgess, Stringer & Co", 1848, Book.Genre.FICTION));
        books.add(new Book("The Oak Openings", "James Fenimore Cooper", "Burgess, Stringer & Co", 1848, Book.Genre.FICTION));
        books.add(new Book("The Sea Lions", "James Fenimore Cooper", "Stringer & Townsend", 1849, Book.Genre.FICTION));
        books.add(new Book("The Ways of the Hour", "James Fenimore Cooper", "G.P. Putnam", 1850, Book.Genre.FICTION));

        return books;
    }
}