// Book API

GET {{url}}/books

###

GET {{url}}/books/2

###

POST {{url}}/books
Content-Type: application/json

{
  "title": "Ny Bog",
  "author": "John Doe",
  "publisher": "Forlag A/S",
  "yearPublished": 2023,
  "genre": "FICTION"
}

###

PUT {{url}}/books/3
Content-Type: application/json

{
  "title": "Opdateret Bog",
  "author": "Jane Smith",
  "publisher": "Nyt Forlag",
  "yearPublished": 2024,
  "genre": "NONFICTION"
}

###

DELETE {{url}}/books/5